<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>HappyGeeks.Wiser.FrontEnd</PackageId>
    <Version>3.4.28</Version>
    <Authors>Happy Geeks B.V.</Authors>
    <Company>Happy Geeks B.V.</Company>
    <Product>Wiser front-end</Product>
    <UserSecretsId>a69118f8-4ce1-4765-b419-31edbd568e39</UserSecretsId>
    <AssemblyVersion>3.4.28.0</AssemblyVersion>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	<LangVersion>14</LangVersion>
	<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <ItemGroup>
    <Content Update="web.config">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="temp\**" />   
    <None Remove="temp\**" />
    <Content Remove="temp\**" />
    <Content Update="Core\Fonts\kendo-font-icons.ttf">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <None Update="Core\Css\partner\bestdeal.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Core\Css\partner\ullasa.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Core\Css\partner\strijbosch-pim.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Core\Css\partner\strijbosch.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Core\Css\partner\reservery.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Core\Css\partner\maindev.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Core\Css\partner\plintenfabriek.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Core\Css\partner\intense.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Core\Css\partner\lockerbox.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Core\Css\partner\eventsafe2.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Core\Css\partner\fixer.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Core\Css\partner\denistel.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Core\Css\partner\eventsafe.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Core\Css\partner\brabantsehoeve.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GoogleAuthenticator" Version="3.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Api\Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modules\Base\Scripts\codemirror\" />
    <Folder Include="wwwroot\fonts\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="temp\**" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\customscripts\bryntum\locale\scheduler.locale.Nl.js" />
  </ItemGroup>
</Project>