name: Publish development

on:
  push:
    branches: 
    - develop
  workflow_dispatch:

jobs:
  deploy-cluster1:
    if: false
    uses: ./.github/workflows/deploy-single-server.yml
    secrets: inherit
    with:
      runner: cluster1_transip
      environment: Development

  deploy-cluster3:
    if: false
    uses: ./.github/workflows/deploy-single-server.yml
    secrets: inherit
    with:
      runner: cluster3_transip
      environment: Development

  deploy-cluster4:
    if: false
    uses: ./.github/workflows/deploy-single-server.yml
    secrets: inherit
    with:
      runner: cluster4_transip
      environment: Development

  deploy-linux:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/deploy-single-linux-server.yml
    secrets: inherit
    with:
      runner: linux_transip
      environment: Development