name: Publish development

on:
  push:
    branches: 
    - develop
  workflow_dispatch:

jobs:
  deploy-cluster1:
    uses: ./.github/workflows/deploy-single-server.yml
    secrets:
      cloudflare_api_key: ${{ secrets.CLOUDFLARE_API_KEY }}
    with:
      runner: cluster1_transip
      environment: Development
      cloudflare_account_id: 737e9d9233ff99af2b322ea397547391
      cloudflare_pool_id: 3f96a062515e3396be07b9ed88499c7b
      cloudflare_origin_id: cluster_1

  deploy-cluster3:
    needs: deploy-cluster1
    uses: ./.github/workflows/deploy-single-server.yml
    secrets:
      cloudflare_api_key: ${{ secrets.CLOUDFLARE_API_KEY }}
    with:
      runner: cluster3_transip
      environment: Development
      cloudflare_account_id: 737e9d9233ff99af2b322ea397547391
      cloudflare_pool_id: 3f96a062515e3396be07b9ed88499c7b
      cloudflare_origin_id: cluster_3

  deploy-cluster4:
    needs: deploy-cluster3
    uses: ./.github/workflows/deploy-single-server.yml
    secrets:
      cloudflare_api_key: ${{ secrets.CLOUDFLARE_API_KEY }}
    with:
      runner: cluster4_transip
      environment: Development
      cloudflare_account_id: 737e9d9233ff99af2b322ea397547391
      cloudflare_pool_id: 3f96a062515e3396be07b9ed88499c7b
      cloudflare_origin_id: cluster_4